In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4,4,5,6]

In [4]:
my_arr = np.array(my_list)

In [5]:
my_arr

array([1, 2, 3, 4, 4, 5, 6])

In [6]:
type(my_arr)

numpy.ndarray

In [12]:
my_2Dlist = [[1,2,3],[4,4,5],[6,1,2]]

In [13]:
my_2darr=np.matrix(my_2Dlist)

In [14]:
print(my_2darr)

[[1 2 3]
 [4 4 5]
 [6 1 2]]


In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [17]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [28]:
np.linspace(0,10,1)

array([0.])

In [32]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.random.rand(4)

array([0.753546  , 0.33546314, 0.58675509, 0.75846715])

In [37]:
np.random.rand(4,4)

array([[0.39342913, 0.45680577, 0.83064848, 0.49000221],
       [0.21915666, 0.833298  , 0.1750748 , 0.0447211 ],
       [0.54975245, 0.69842803, 0.97142282, 0.69873924],
       [0.39297676, 0.39401288, 0.70164724, 0.99570627]])

In [38]:
np.random.randn(4)

array([-0.69110314,  0.22101705,  1.04956896, -0.28867952])

In [41]:
np.random.randn(4,4)

array([[-0.97313249,  0.29419347, -0.86293312, -1.66011089],
       [-0.1539756 , -0.84613001,  0.88874404,  0.52531979],
       [-0.86482668, -0.55427905, -0.73788708,  0.25983761],
       [ 1.27548903, -0.16512844,  0.81496732,  1.67312233]])

In [52]:
np.random.randint(1,100)

8

In [53]:
np.random.randint(1,100,10)

array([47, 54, 97, 22, 41, 41, 61,  6,  7, 21])

In [54]:
arr = np.arange(25)

In [55]:
type(arr)

numpy.ndarray

In [56]:
arrays = np.random.randint(1,100,25)

In [57]:
type(arrays)

numpy.ndarray

In [58]:
arrays.shape

(25,)

In [59]:
arrays.reshape(25,1)

array([[ 7],
       [75],
       [70],
       [21],
       [51],
       [40],
       [ 1],
       [51],
       [70],
       [35],
       [81],
       [ 6],
       [ 3],
       [51],
       [32],
       [ 8],
       [40],
       [38],
       [ 8],
       [72],
       [82],
       [37],
       [20],
       [70],
       [32]])

In [60]:
arrays.shape

(25,)

In [61]:
arrays.reshape(5,5)

array([[ 7, 75, 70, 21, 51],
       [40,  1, 51, 70, 35],
       [81,  6,  3, 51, 32],
       [ 8, 40, 38,  8, 72],
       [82, 37, 20, 70, 32]])

In [62]:
arrays.reshape(6,2)

ValueError: cannot reshape array of size 25 into shape (6,2)

In [63]:
arrays.reshape(5,5).shape

(5, 5)

In [64]:
arrays

array([ 7, 75, 70, 21, 51, 40,  1, 51, 70, 35, 81,  6,  3, 51, 32,  8, 40,
       38,  8, 72, 82, 37, 20, 70, 32])

In [65]:
arrays.min()

1

In [66]:
arrays.argmin()

6

In [67]:
arrays.max()

82

In [69]:
arrays.argmax()

20

In [70]:
arrays.dtype

dtype('int32')

In [78]:
names = np.array(['manish','abc','ok'])

In [79]:
names.dtype

dtype('<U6')

In [81]:
names.max()

TypeError: cannot perform reduce with flexible type

In [80]:
nums = np.array([0.2,1.3,5.8])

In [82]:
nums.dtype

dtype('float64')

In [83]:
nums = np.array([0.2,1,2])
nums.dtype

dtype('float64')

In [84]:
nums = np.array([0.2,1,2,'man'])
nums.dtype

dtype('<U32')