https://jakevdp.github.io/PythonDataScienceHandbook/

In [73]:
import numpy as np

In [3]:
my_list = [1,2,3,4,4,5,6]

In [4]:
my_arr = np.array(my_list)

In [5]:
my_arr

array([1, 2, 3, 4, 4, 5, 6])

In [6]:
type(my_arr)

numpy.ndarray

In [12]:
my_2Dlist = [[1,2,3],[4,4,5],[6,1,2]]

In [13]:
my_2darr=np.matrix(my_2Dlist)

In [14]:
print(my_2darr)

[[1 2 3]
 [4 4 5]
 [6 1 2]]


In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [17]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [28]:
np.linspace(0,10,1)

array([0.])

In [32]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.random.rand(4)

array([0.753546  , 0.33546314, 0.58675509, 0.75846715])

In [37]:
np.random.rand(4,4)

array([[0.39342913, 0.45680577, 0.83064848, 0.49000221],
       [0.21915666, 0.833298  , 0.1750748 , 0.0447211 ],
       [0.54975245, 0.69842803, 0.97142282, 0.69873924],
       [0.39297676, 0.39401288, 0.70164724, 0.99570627]])

In [38]:
np.random.randn(4)

array([-0.69110314,  0.22101705,  1.04956896, -0.28867952])

In [41]:
np.random.randn(4,4)

array([[-0.97313249,  0.29419347, -0.86293312, -1.66011089],
       [-0.1539756 , -0.84613001,  0.88874404,  0.52531979],
       [-0.86482668, -0.55427905, -0.73788708,  0.25983761],
       [ 1.27548903, -0.16512844,  0.81496732,  1.67312233]])

In [52]:
np.random.randint(1,100)

8

In [53]:
np.random.randint(1,100,10)

array([47, 54, 97, 22, 41, 41, 61,  6,  7, 21])

In [54]:
arr = np.arange(25)

In [55]:
type(arr)

numpy.ndarray

In [56]:
arrays = np.random.randint(1,100,25)

In [57]:
type(arrays)

numpy.ndarray

In [58]:
arrays.shape

(25,)

In [59]:
arrays.reshape(25,1)

array([[ 7],
       [75],
       [70],
       [21],
       [51],
       [40],
       [ 1],
       [51],
       [70],
       [35],
       [81],
       [ 6],
       [ 3],
       [51],
       [32],
       [ 8],
       [40],
       [38],
       [ 8],
       [72],
       [82],
       [37],
       [20],
       [70],
       [32]])

In [60]:
arrays.shape

(25,)

In [61]:
arrays.reshape(5,5)

array([[ 7, 75, 70, 21, 51],
       [40,  1, 51, 70, 35],
       [81,  6,  3, 51, 32],
       [ 8, 40, 38,  8, 72],
       [82, 37, 20, 70, 32]])

In [62]:
arrays.reshape(6,2)

ValueError: cannot reshape array of size 25 into shape (6,2)

In [63]:
arrays.reshape(5,5).shape

(5, 5)

In [64]:
arrays

array([ 7, 75, 70, 21, 51, 40,  1, 51, 70, 35, 81,  6,  3, 51, 32,  8, 40,
       38,  8, 72, 82, 37, 20, 70, 32])

In [65]:
arrays.min()

1

In [66]:
arrays.argmin()

6

In [67]:
arrays.max()

82

In [69]:
arrays.argmax()

20

In [70]:
arrays.dtype

dtype('int32')

In [78]:
names = np.array(['manish','abc','ok'])

In [79]:
names.dtype

dtype('<U6')

In [81]:
names.max()

TypeError: cannot perform reduce with flexible type

In [80]:
nums = np.array([0.2,1.3,5.8])

In [82]:
nums.dtype

dtype('float64')

In [83]:
nums = np.array([0.2,1,2])
nums.dtype

dtype('float64')

In [84]:
nums = np.array([0.2,1,2,'man'])
nums.dtype

dtype('<U32')

In [3]:
import numpy as np
arr = np.arange(20,40)

In [4]:
arr[8]

28

In [5]:
arr[:3]

array([20, 21, 22])

In [6]:
arr[4:3]

array([], dtype=int32)

In [7]:
arr[0:3]

array([20, 21, 22])

In [8]:
arr[3:]

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [10]:
#print values from 3rd item to 10th item
arr[2:10]

array([22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
arr[1:5]=100
arr

array([ 20, 100, 100, 100, 100,  25,  26,  27,  28,  29,  30,  31,  32,
        33,  34,  35,  36,  37,  38,  39])

In [15]:
arr[19]=100
arr

array([ 20, 100, 100, 100, 100,  25,  26,  27,  28,  29,  30,  31,  32,
        33,  34,  35,  36,  37,  38, 100])

In [16]:
arr[:]

array([ 20, 100, 100, 100, 100,  25,  26,  27,  28,  29,  30,  31,  32,
        33,  34,  35,  36,  37,  38, 100])

In [18]:
arr[:]=1
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
#if take a slice and makes changes to the slice then the original data set will also change

In [19]:
a = np.arange(0,10)

In [21]:
slice = a[:4]
slice

array([0, 1, 2, 3])

In [22]:
slice[:] = 99

In [23]:
slice

array([99, 99, 99, 99])

In [24]:
# Plz Note the original will also change
a

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9])

In [25]:
a_copy=a.copy()
a_copy

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9])

In [26]:
b=a_copy[0:4]

In [27]:
b

array([99, 99, 99, 99])

In [29]:
b[:]=0
b

array([0, 0, 0, 0])

In [30]:
a_copy

array([0, 0, 0, 0, 4, 5, 6, 7, 8, 9])

In [31]:
# this time our original data set didnt got change
a

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9])

In [33]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr2d.shape

(3, 3)

In [35]:
arr2d[0]

array([1, 2, 3])

In [36]:
arr2d[0][0]

1

In [37]:
arr2d[0][1]

2

In [38]:
arr2d[0][2]

3

In [40]:
arr2d[2][1]

8

In [41]:
arr2d[2][0:2]

array([7, 8])

In [42]:
arr2d[2,0:2]

array([7, 8])

In [43]:
#instead of wiriting separate [] we can use ,
arr2d[0,0]

1

In [ ]:
arr2d[0,0]

In [46]:
arr2d[1,0:2]

array([4, 5])

In [47]:
arr2d[1,0:]

array([4, 5, 6])

In [54]:
arr2d[:2,0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr2d[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2d[[0,2],0:]

array([[1, 2, 3],
       [7, 8, 9]])

In [56]:
arr2d[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [57]:
arr2d[[0,2],0]

array([1, 7])

In [58]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [61]:
boolar = arr > 4
boolar

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [62]:
arr[boolar]

array([5, 6, 7, 8, 9])

In [63]:
arr[arr>2]

array([3, 4, 5, 6, 7, 8, 9])

In [65]:
x=2
arr[arr>=2]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
mask = np.array([1,0,0,1],dtype = 'bool')
mask

array([ True, False, False,  True])

In [72]:
import numpy as np 

x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print(x) 
print(y) 
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [74]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [76]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [77]:
# Create a 3x5 array filled with 3.14
np.full(5, 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14])

In [78]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.50273314, -1.23338966, -0.62579321],
       [ 0.87210896, -0.18988909,  0.92444969],
       [-0.65682124, -0.49537827,  0.42668449]])

In [82]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [84]:
x1

array([5, 0, 3, 3, 7, 9])

In [86]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [85]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [87]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [88]:
x = np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [90]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [91]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [92]:
x[::3]

array([0, 3, 6, 9])

In [93]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [94]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [98]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape(1, 3)

array([[1, 2, 3]])

In [97]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [99]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [100]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [101]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [102]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [103]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [104]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [105]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [106]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [107]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [109]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 6])
print(x1, x2, x3)

[1 2 3] [99 99  3] [2 1]


In [110]:
np.power(2,3)

8


Operator	Equivalent ufunc	Description
+	np.add	Addition (e.g., 1 + 1 = 2)
-	np.subtract	Subtraction (e.g., 3 - 2 = 1)
-	np.negative	Unary negation (e.g., -2)
*	np.multiply	Multiplication (e.g., 2 * 3 = 6)
/	np.divide	Division (e.g., 3 / 2 = 1.5)
//	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
**	np.power	Exponentiation (e.g., 2 ** 3 = 8)
%	np.mod	Modulus/remainder (e.g., 9 % 4 = 1)

In [111]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [112]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [113]:
theta = np.linspace(0, np.pi, 3)

In [114]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [115]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [116]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [121]:
heights=[189, 170, 189 ,163 ,183 ,171 ,185, 168, 173, 183, 173, 173, 175, 178, 183 ,193, 178 ,173,
 174 ,183 ,183 ,168, 170, 178 ,182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182 ,183,
 177 ,185 ,188 ,188 ,182 ,185]
print("25th percentile:   ", np.percentile(heights, 25))
print("Median:            ", np.median(heights))
print("75th percentile:   ", np.percentile(heights, 75))

25th percentile:    174.25
Median:             182.0
75th percentile:    183.0


In [128]:
print("Mean height:       ", np.array(heights).mean())
print("Standard deviation:", np.array(heights).std())
print("Minimum height:    ", np.array(heights).min())
print("Maximum height:    ", np.array(heights).max())

Mean height:        179.73809523809524
Standard deviation: 6.931843442745892
Minimum height:     163
Maximum height:     193


In [134]:
x = np.arange(10)
np.count_nonzero(x < 6)

6

In [136]:
sum(x<6)

6

In [137]:
# are there any values greater than 8?
np.any(x > 8)

True

In [138]:
# are there any values less than zero?
np.any(x < 0)

False

In [139]:
# are all values less than 10?
np.all(x < 10)

True

In [140]:
# are all values equal to 6?
np.all(x == 6)

False

In [141]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [142]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [143]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [144]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [145]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [146]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [147]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 5)

array([2, 1, 3, 4, 5, 6, 7])